FROM nginx:alpine


# Copy custom nginx configuration from app/backend/API-gateway
COPY app/backend/API-gateway/nginx.conf /etc/nginx/nginx.conf

# Create log directory
RUN mkdir -p /var/log/nginx

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]